// Re-export only the types from @kubernetes/client-node
// This works because TypeScript will strip these during compilation
// and won't try to bundle the actual runtime code

export type {
  V1NetworkPolicyPort,
  V1NetworkPolicyPeer,
  V1NetworkPolicyEgressRule,
  V1LoadBalancerStatus,
  V1Condition,
  V1Deployment,
  V1DeploymentList,
  V1DeploymentSpec,
  V1DeploymentStatus,
  V1Pod,
  V1PodList,
  V1PodSpec,
  V1PodStatus,
  V1PodCondition,
  V1Container,
  V1ContainerPort,
  V1ContainerStatus,
  V1ObjectMeta,
  V1ListMeta,
  V1RoleBinding,
  V1RoleBindingList,
  V1ClusterRoleBinding,
  V1ClusterRoleBindingList,
  V1Role,
  V1RoleList,
  V1ClusterRole,
  V1ClusterRoleList,
  V1Service,
  V1ServiceList,
  V1ServiceSpec,
  V1ServiceStatus,
  V1Namespace,
  V1NamespaceList,
  V1ConfigMap,
  V1ConfigMapList,
  V1Secret,
  V1SecretList,
  V1Node,
  V1NodeList,
  V1PersistentVolume,
  V1PersistentVolumeList,
  V1PersistentVolumeClaim,
  V1PersistentVolumeClaimList,
  V1StorageClass,
  V1StorageClassList,
  V1StatefulSet,
  V1StatefulSetList,
  V1DaemonSet,
  V1DaemonSetList,
  V1ReplicaSet,
  V1ReplicaSetList,
  V1Job,
  V1JobList,
  V1CronJob,
  V1CronJobList,
  V1Ingress,
  V1IngressList,
  V1IngressClass,
  V1IngressClassList,
  V1NetworkPolicy,
  V1NetworkPolicyList,
  V1ResourceQuota,
  V1ResourceQuotaList,
  V1LimitRange,
  V1LimitRangeList,
  V1LimitRangeItem,
  V1HorizontalPodAutoscaler,
  V1HorizontalPodAutoscalerList,
  V1ServiceAccount,
  V1ServiceAccountList,
  V1Endpoint,
  V1Endpoints,
  V1EndpointsList,
  V1EndpointSlice,
  V1EndpointSliceList,
  V1PodDisruptionBudget,
  V1PodDisruptionBudgetList,
  V1PriorityClass,
  V1PriorityClassList,
  V1RuntimeClass,
  V1RuntimeClassList,
  V1CSIDriver,
  V1CSIDriverList,
  V1CSINode,
  V1CSINodeList,
  V1VolumeAttachment,
  V1VolumeAttachmentList,
  V1MutatingWebhookConfiguration,
  V1MutatingWebhookConfigurationList,
  V1ValidatingWebhookConfiguration,
  V1ValidatingWebhookConfigurationList,
  V1CustomResourceDefinition,
  V1CustomResourceDefinitionList,
  CoreV1Event,
  CoreV1EventList,
  V2HorizontalPodAutoscaler,
  V2HorizontalPodAutoscalerList,
  NodeStatus,
  V1OwnerReference,
  Context,
  V1ResourceQuotaStatus,
  V1ManagedFieldsEntry,
  V1ResourceQuotaSpec,
  V1ScopeSelector,
  V1ScopedResourceSelectorRequirement,
  V2HorizontalPodAutoscalerSpec,
  V2HorizontalPodAutoscalerStatus,
  V2HorizontalPodAutoscalerBehavior,
  V2HPAScalingRules,
  V2HPAScalingPolicy,
  V2MetricSpec,
  V2MetricStatus,
  V2ResourceMetricSource,
  V2ResourceMetricStatus,
  V2ExternalMetricSource,
  V2ExternalMetricStatus,
  V2ObjectMetricSource,
  V2ObjectMetricStatus,
  V2PodsMetricSource,
  V2PodsMetricStatus,
  V2CrossVersionObjectReference,
  V2HorizontalPodAutoscalerCondition,
  // Additional V1 types
  V1Affinity,
  V1AppArmorProfile,
  V1AWSElasticBlockStoreVolumeSource,
  V1AzureDiskVolumeSource,
  V1AzureFilePersistentVolumeSource,
  V1AzureFileVolumeSource,
  V1Capabilities,
  V1CephFSPersistentVolumeSource,
  V1CephFSVolumeSource,
  V1CinderPersistentVolumeSource,
  V1CinderVolumeSource,
  V1ClientIPConfig,
  V1ClusterTrustBundleProjection,
  V1ConfigMapEnvSource,
  V1ConfigMapKeySelector,
  V1ConfigMapProjection,
  V1ConfigMapVolumeSource,
  V1ContainerResizePolicy,
  V1ContainerState,
  V1ContainerStateRunning,
  V1ContainerStateTerminated,
  V1ContainerStateWaiting,
  V1CronJobSpec,
  V1CronJobStatus,
  V1CrossVersionObjectReference,
  V1CSIDriverSpec,
  V1CSINodeDriver,
  V1CSINodeSpec,
  V1CSIPersistentVolumeSource,
  V1CSIVolumeSource,
  V1DaemonSetCondition,
  V1DaemonSetSpec,
  V1DaemonSetStatus,
  V1DaemonSetUpdateStrategy,
  V1DeploymentCondition,
  V1DeploymentStrategy,
  V1DownwardAPIProjection,
  V1DownwardAPIVolumeFile,
  V1DownwardAPIVolumeSource,
  V1EmptyDirVolumeSource,
  V1EndpointAddress,
  V1EndpointConditions,
  V1EndpointHints,
  V1EndpointSubset,
  V1EnvFromSource,
  V1EnvVar,
  V1EnvVarSource,
  V1EphemeralContainer,
  V1EphemeralVolumeSource,
  V1ExecAction,
  V1FCVolumeSource,
  V1FlexPersistentVolumeSource,
  V1FlexVolumeSource,
  V1FlockerVolumeSource,
  V1GCEPersistentDiskVolumeSource,
  V1GitRepoVolumeSource,
  V1GlusterfsPersistentVolumeSource,
  V1GlusterfsVolumeSource,
  V1GRPCAction,
  V1HorizontalPodAutoscalerSpec,
  V1HorizontalPodAutoscalerStatus,
  V1HostAlias,
  V1HostIP,
  V1HostPathVolumeSource,
  V1HTTPGetAction,
  V1HTTPHeader,
  V1HTTPIngressPath,
  V1HTTPIngressRuleValue,
  V1IngressBackend,
  V1IngressClassParametersReference,
  V1IngressClassSpec,
  V1IngressLoadBalancerIngress,
  V1IngressLoadBalancerStatus,
  V1IngressPortStatus,
  V1IngressRule,
  V1IngressServiceBackend,
  V1IngressSpec,
  V1IngressStatus,
  V1IngressTLS,
  V1IPBlock,
  V1ISCSIPersistentVolumeSource,
  V1ISCSIVolumeSource,
  V1JobCondition,
  V1JobSpec,
  V1JobStatus,
  V1JobTemplateSpec,
  V1KeyToPath,
  V1LabelSelector,
  V1LabelSelectorRequirement,
  V1Lifecycle,
  V1LifecycleHandler,
  V1LimitRangeSpec,
  V1LoadBalancerIngress,
  V1LocalObjectReference,
  V1LocalVolumeSource,
  V1ModifyVolumeStatus,
  V1NetworkPolicyIngressRule,
  V1NetworkPolicySpec,
  V1NFSVolumeSource,
  V1NodeAffinity,
  V1NodeSelector,
  V1NodeSelectorRequirement,
  V1NodeSelectorTerm,
  V1ObjectFieldSelector,
  V1ObjectReference,
  V1PersistentVolumeClaimCondition,
  V1PersistentVolumeClaimSpec,
  V1PersistentVolumeClaimStatus,
  V1PersistentVolumeClaimTemplate,
  V1PersistentVolumeClaimVolumeSource,
  V1PersistentVolumeSpec,
  V1PersistentVolumeStatus,
  V1PhotonPersistentDiskVolumeSource,
  V1PodAffinity,
  V1PodAffinityTerm,
  V1PodAntiAffinity,
  V1PodDisruptionBudgetSpec,
  V1PodDisruptionBudgetStatus,
  V1PodDNSConfig,
  V1PodDNSConfigOption,
  V1PodFailurePolicy,
  V1PodFailurePolicyOnExitCodesRequirement,
  V1PodFailurePolicyOnPodConditionsPattern,
  V1PodFailurePolicyRule,
  V1PodIP,
  V1PodOS,
  V1PodReadinessGate,
  V1PodResourceClaim,
  V1PodResourceClaimStatus,
  V1PodSchedulingGate,
  V1PodSecurityContext,
  V1PodTemplateSpec,
  V1PortStatus,
  V1PortworxVolumeSource,
  V1PreferredSchedulingTerm,
  V1Probe,
  V1ProjectedVolumeSource,
  V1QuobyteVolumeSource,
  V1RBDPersistentVolumeSource,
  V1RBDVolumeSource,
  V1ReplicaSetCondition,
  V1ReplicaSetSpec,
  V1ReplicaSetStatus,
  V1ResourceClaim,
  V1ResourceFieldSelector,
  V1ResourceRequirements,
  V1RollingUpdateDaemonSet,
  V1RollingUpdateDeployment,
  V1RollingUpdateStatefulSetStrategy,
  V1ScaleIOPersistentVolumeSource,
  V1ScaleIOVolumeSource,
  V1SeccompProfile,
  V1SecretEnvSource,
  V1SecretKeySelector,
  V1SecretProjection,
  V1SecretReference,
  V1SecretVolumeSource,
  V1SecurityContext,
  V1SELinuxOptions,
  V1ServiceAccountTokenProjection,
  V1ServiceBackendPort,
  V1ServicePort,
  V1SessionAffinityConfig,
  V1SleepAction,
  V1StatefulSetCondition,
  V1StatefulSetOrdinals,
  V1StatefulSetPersistentVolumeClaimRetentionPolicy,
  V1StatefulSetSpec,
  V1StatefulSetStatus,
  V1StatefulSetUpdateStrategy,
  V1StorageOSPersistentVolumeSource,
  V1StorageOSVolumeSource,
  V1SuccessPolicy,
  V1SuccessPolicyRule,
  V1Sysctl,
  V1TCPSocketAction,
  V1Toleration,
  V1TopologySpreadConstraint,
  V1TypedLocalObjectReference,
  V1TypedObjectReference,
  V1UncountedTerminatedPods,
  V1Volume,
  V1VolumeDevice,
  V1VolumeMount,
  V1VolumeMountStatus,
  V1VolumeNodeAffinity,
  V1VolumeNodeResources,
  V1VolumeProjection,
  V1VolumeResourceRequirements,
  V1VsphereVirtualDiskVolumeSource,
  V1WeightedPodAffinityTerm,
  V1WindowsSecurityContextOptions,
  // Additional V2 types
  V2ContainerResourceMetricSource,
  V2ContainerResourceMetricStatus,
  V2MetricIdentifier,
  V2MetricTarget,
  V2MetricValueStatus,
} from '@kubernetes/client-node';

// Stub types for components that reference non-existent Kubernetes types
// These are placeholders to fix TypeScript errors
export interface V1ContainerUser {
  uid?: number;
  gid?: number;
  username?: string;
}

export interface V1ForNode {
  name?: string;
}

export interface V1ForZone {
  name?: string;
}

export interface V1ImageVolumeSource {
  reference?: string;
  pullPolicy?: string;
}

export interface V1LinuxContainerUser {
  uid?: number;
  gid?: number;
  supplementalGroups?: number[];
}

export interface V1ResourceHealth {
  resourceID?: string;
  health?: string;
}

export interface V1ResourceStatus {
  name?: string;
  resources?: any;
}