import { Resources } from '@utils/enums';
import { ResourceActionConfigs } from '../ResourceActions.types';

export const resourceActionConfigs: ResourceActionConfigs = {
  [Resources.Pods]: {
    supportsDelete: true,
    supportsEdit: false,
    supportsPortForward: true,
    supportsScale: false,
    supportsLogs: true,
  },
  [Resources.Deployments]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: true,
    supportsLogs: true,
  },
  [Resources.Services]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: true,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.Namespaces]: {
    supportsDelete: true,
    supportsEdit: false,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.Nodes]: {
    supportsDelete: false,
    supportsEdit: false,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.Secrets]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.ConfigMaps]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.StatefulSets]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: true,
    supportsLogs: true,
  },
  [Resources.DaemonSets]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: true,
  },
  [Resources.ReplicaSets]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: true,
    supportsLogs: true,
  },
  [Resources.Jobs]: {
    supportsDelete: true,
    supportsEdit: false,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: true,
  },
  [Resources.CronJobs]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.Ingresses]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.NetworkPolicies]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.PersistentVolumes]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.PersistentVolumeClaims]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.StorageClasses]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.ServiceAccounts]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.Roles]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.RoleBindings]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.ClusterRoles]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.ClusterRoleBindings]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.ResourceQuotas]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.LimitRanges]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.HorizontalPodAutoscalers]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.VerticalPodAutoscalers]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.PodDisruptionBudgets]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.PriorityClasses]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.RuntimeClasses]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
  [Resources.CustomResourceDefinitions]: {
    supportsDelete: true,
    supportsEdit: true,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  },
};

export function getResourceActionConfig(resourceType: Resources): ResourceActionConfig {
  return resourceActionConfigs[resourceType] || {
    supportsDelete: false,
    supportsEdit: false,
    supportsPortForward: false,
    supportsScale: false,
    supportsLogs: false,
  };
}