resourceName: V1RollingUpdateDeployment
properties:
  maxSurge:
    type: IntOrString
    optional: true
    description: IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
  maxUnavailable:
    type: IntOrString
    optional: true
    description: IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
description: Spec to control the desired behavior of rolling update.
