import { app, BrowserWindow, ipcMain, shell } from 'electron';
import k8s = require('@kubernetes/client-node');
import * as net from 'net';
import { v4 as uuidv4 } from 'uuid';
import { spawn, ChildProcess } from 'child_process';
import { PortForwardInfo, PortForwardRequest } from '../renderer/utils/types';
import { PortForwardStatus } from '../renderer/utils/enums';
import { startMCPServer, stopMCPServer, getToolCallHistory, getActiveConnections, clearToolCallHistory } from './mcp-server';

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sCoreV1Api = kc.makeApiClient(k8s.CoreV1Api);
const k8sAppsV1Api = kc.makeApiClient(k8s.AppsV1Api);
const k8sBatchV1Api = kc.makeApiClient(k8s.BatchV1Api);
const k8sNetworkingV1Api = kc.makeApiClient(k8s.NetworkingV1Api);
const k8sDiscoveryV1Api = kc.makeApiClient(k8s.DiscoveryV1Api);
const k8sAutoscalingV2Api = kc.makeApiClient(k8s.AutoscalingV2Api);
const k8sPolicyV1Api = kc.makeApiClient(k8s.PolicyV1Api);
const k8sStorageV1Api = kc.makeApiClient(k8s.StorageV1Api);
const k8sRbacAuthorizationV1Api = kc.makeApiClient(k8s.RbacAuthorizationV1Api);
const k8sSchedulingV1Api = kc.makeApiClient(k8s.SchedulingV1Api);
const k8sNodeV1Api = kc.makeApiClient(k8s.NodeV1Api);
const k8sAdmissionregistrationV1Api = kc.makeApiClient(k8s.AdmissionregistrationV1Api);
const k8sApiextensionsV1Api = kc.makeApiClient(k8s.ApiextensionsV1Api);
const k8sCustomObjectsApi = kc.makeApiClient(k8s.CustomObjectsApi);


// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.removeMenu()

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  createWindow();
  
  // Start MCP server
  try {
    await startMCPServer();
  } catch (error) {
    console.error('Failed to start MCP server:', error);
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
// Handle the getPods request from the renderer

ipcMain.handle('openExternalLink', (event, url) => {
  shell.openExternal(url);
});

// Contexts
ipcMain.handle('getContexts', () => (kc.getContexts()));
ipcMain.handle('getCurrentContext', () => (kc.getCurrentContext()));
ipcMain.handle('setCurrentContext', (event, name) => (kc.setCurrentContext(name)));
ipcMain.handle('getContextObject', (event, name) => (kc.getContextObject(name)));
ipcMain.handle('addContext', (event, context) => (kc.addContext(context)));

// Nodes
ipcMain.handle('listNode', async () => (await k8sCoreV1Api.listNode()).body);
ipcMain.handle('readNode', async (event, name) => (await k8sCoreV1Api.readNode(name)).body);
ipcMain.handle('topNodes', async () => (await k8s.topNodes(k8sCoreV1Api)));
ipcMain.handle('cordonNode', async (event, name) => {
  try {
    const patch = {
      spec: {
        unschedulable: true
      }
    };
    const response = await k8sCoreV1Api.patchNode(
      name, 
      patch, 
      undefined, 
      undefined, 
      undefined, 
      undefined, 
      undefined,
      { headers: { 'Content-Type': k8s.PatchUtils.PATCH_FORMAT_STRATEGIC_MERGE_PATCH } }
    );
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while cordoning the node';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('uncordonNode', async (event, name) => {
  try {
    const patch = {
      spec: {
        unschedulable: false
      }
    };
    const response = await k8sCoreV1Api.patchNode(
      name, 
      patch, 
      undefined, 
      undefined, 
      undefined, 
      undefined, 
      undefined,
      { headers: { 'Content-Type': k8s.PatchUtils.PATCH_FORMAT_STRATEGIC_MERGE_PATCH } }
    );
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while uncordoning the node';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});


// Namespaces
ipcMain.handle('listNamespace', async () => (await k8sCoreV1Api.listNamespace()).body);
ipcMain.handle('readNamespace', async (event, name) => (await k8sCoreV1Api.readNamespace(name)).body);
ipcMain.handle('createNamespace', async (event, payload) => {
  try {
    const response = await k8sCoreV1Api.createNamespace(payload);
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while creating the namespace';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('deleteNamespace', async (event, name) => (await k8sCoreV1Api.deleteNamespace(name)).body);


// Deployments
ipcMain.handle('listDeploymentForAllNamespaces', async () => (await k8sAppsV1Api.listDeploymentForAllNamespaces()).body);
ipcMain.handle('readNamespacedDeployment', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedDeployment(name, namespace)).body);


// ReplicaSets
ipcMain.handle('listReplicaSetForAllNamespaces', async () => (await k8sAppsV1Api.listReplicaSetForAllNamespaces()).body);
ipcMain.handle('readNamespacedReplicaSet', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedReplicaSet(name, namespace)).body);


// StatefulSets
ipcMain.handle('listStatefulSetForAllNamespaces', async () => (await k8sAppsV1Api.listStatefulSetForAllNamespaces()).body);
ipcMain.handle('readNamespacedStatefulSet', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedStatefulSet(name, namespace)).body);


// DaemonSets
ipcMain.handle('listDaemonSetForAllNamespaces', async () => (await k8sAppsV1Api.listDaemonSetForAllNamespaces()).body);
ipcMain.handle('readNamespacedDaemonSet', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedDaemonSet(name, namespace)).body);


// Pods
ipcMain.handle('listPodForAllNamespaces', async () => (await k8sCoreV1Api.listPodForAllNamespaces()).body);
ipcMain.handle('readNamespacedPod', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedPod(name, namespace)).body);
ipcMain.handle('createNamespacedPod', async (event, namespace, podSpec) => {
  try {
    const response = await k8sCoreV1Api.createNamespacedPod(namespace, podSpec);
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while creating the pod';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('deleteNamespacedPod', async (event, name, namespace) => (await k8sCoreV1Api.deleteNamespacedPod(name, namespace)).body);

// Pod logs
ipcMain.handle('readNamespacedPodLog', async (event, name, namespace, container, options = {}) => {
  try {
    const response = await k8sCoreV1Api.readNamespacedPodLog(
      name,
      namespace,
      container,
      options.follow,
      undefined, // insecureSkipTLSVerifyBackend
      undefined, // limitBytes
      options.pretty,
      options.previous,
      options.sinceSeconds,
      options.tailLines,
      options.timestamps
    );
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while fetching pod logs';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});


// ConfigMaps
ipcMain.handle('listConfigMapForAllNamespaces', async () => (await k8sCoreV1Api.listConfigMapForAllNamespaces()).body);
ipcMain.handle('readNamespacedConfigMap', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedConfigMap(name, namespace)).body);
ipcMain.handle('createNamespacedConfigMap', async (event, namespace, payload) => {
  try {
    const response = await k8sCoreV1Api.createNamespacedConfigMap(namespace, payload);
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while creating the config map';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('deleteNamespacedConfigMap', async (event, name, namespace) => (await k8sCoreV1Api.deleteNamespacedConfigMap(name, namespace)).body);




ipcMain.handle('listJobForAllNamespaces', async () => (await k8sBatchV1Api.listJobForAllNamespaces()).body);
ipcMain.handle('listCronJobForAllNamespaces', async () => (await k8sBatchV1Api.listCronJobForAllNamespaces()).body);
ipcMain.handle('readNamespacedCronJob', async (event, name, namespace) => (await k8sBatchV1Api.readNamespacedCronJob(name, namespace)).body);
ipcMain.handle('readNamespacedJob', async (event, name, namespace) => (await k8sBatchV1Api.readNamespacedJob(name, namespace)).body);


ipcMain.handle('listServiceForAllNamespaces', async () => (await k8sCoreV1Api.listServiceForAllNamespaces()).body);
ipcMain.handle('listEndpointsForAllNamespaces', async () => (await k8sCoreV1Api.listEndpointsForAllNamespaces()).body);

ipcMain.handle('listSecretForAllNamespaces', async () => (await k8sCoreV1Api.listSecretForAllNamespaces()).body);
ipcMain.handle('listResourceQuotaForAllNamespaces', async () => (await k8sCoreV1Api.listResourceQuotaForAllNamespaces()).body);
ipcMain.handle('listLimitRangeForAllNamespaces', async () => (await k8sCoreV1Api.listLimitRangeForAllNamespaces()).body);
ipcMain.handle('listPersistentVolumeClaimForAllNamespaces', async () => (await k8sCoreV1Api.listPersistentVolumeClaimForAllNamespaces()).body);
ipcMain.handle('listPersistentVolume', async () => (await k8sCoreV1Api.listPersistentVolume()).body);
ipcMain.handle('listServiceAccountForAllNamespaces', async () => (await k8sCoreV1Api.listServiceAccountForAllNamespaces()).body);
ipcMain.handle('listNamespacedPod', async (event, namespace, ...args) => (await k8sCoreV1Api.listNamespacedPod(namespace, ...args)).body);

ipcMain.handle('readNamespacedService', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedService(name, namespace)).body);

ipcMain.handle('readNamespacedSecret', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedSecret(name, namespace)).body);
ipcMain.handle('readNamespacedResourceQuota', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedResourceQuota(name, namespace)).body);
ipcMain.handle('readNamespacedLimitRange', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedLimitRange(name, namespace)).body);
ipcMain.handle('readNamespacedEndpoints', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedEndpoints(name, namespace)).body);

ipcMain.handle('readNamespacedServiceAccount', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedServiceAccount(name, namespace)).body);
ipcMain.handle('readNamespacedPersistentVolumeClaim', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedPersistentVolumeClaim(name, namespace)).body);
ipcMain.handle('readPersistentVolume', async (event, name) => (await k8sCoreV1Api.readPersistentVolume(name)).body);



ipcMain.handle('listIngressForAllNamespaces', async () => (await k8sNetworkingV1Api.listIngressForAllNamespaces()).body);
ipcMain.handle('listIngressClass', async () => (await k8sNetworkingV1Api.listIngressClass()).body);
ipcMain.handle('listNetworkPolicyForAllNamespaces', async () => (await k8sNetworkingV1Api.listNetworkPolicyForAllNamespaces()).body);
ipcMain.handle('readNamespacedIngress', async (event, name, namespace) => (await k8sNetworkingV1Api.readNamespacedIngress(name, namespace)).body);
ipcMain.handle('readIngressClass', async (event, name) => (await k8sNetworkingV1Api.readIngressClass(name)).body);
ipcMain.handle('readNamespacedNetworkPolicy', async (event, name, namespace) => (await k8sNetworkingV1Api.readNamespacedNetworkPolicy(name, namespace)).body);


ipcMain.handle('listEndpointSliceForAllNamespaces', async () => (await k8sDiscoveryV1Api.listEndpointSliceForAllNamespaces()).body);
ipcMain.handle('readNamespacedEndpointSlice', async (event, name, namespace) => (await k8sDiscoveryV1Api.readNamespacedEndpointSlice(name, namespace)).body);


ipcMain.handle('listVolumeAttachment', async () => (await k8sStorageV1Api.listVolumeAttachment()).body);
ipcMain.handle('listStorageClass', async () => (await k8sStorageV1Api.listStorageClass()).body);
ipcMain.handle('listCSINode', async () => (await k8sStorageV1Api.listCSINode()).body);
ipcMain.handle('listCSIDriver', async () => (await k8sStorageV1Api.listCSIDriver()).body);
ipcMain.handle('readCSIDriver', async (event, name) => (await k8sStorageV1Api.readCSIDriver(name)).body);
ipcMain.handle('readCSINode', async (event, name) => (await k8sStorageV1Api.readCSINode(name)).body);
ipcMain.handle('readStorageClass', async (event, name) => (await k8sStorageV1Api.readStorageClass(name)).body);
ipcMain.handle('readVolumeAttachment', async (event, name) => (await k8sStorageV1Api.readVolumeAttachment(name)).body);


ipcMain.handle('listHorizontalPodAutoscalerForAllNamespaces', async () => (await k8sAutoscalingV2Api.listHorizontalPodAutoscalerForAllNamespaces()).body);
ipcMain.handle('readNamespacedHorizontalPodAutoscaler', async (event, name, namespace) => (await k8sAutoscalingV2Api.readNamespacedHorizontalPodAutoscaler(name, namespace)).body);


ipcMain.handle('listPodDisruptionBudgetForAllNamespaces', async () => (await k8sPolicyV1Api.listPodDisruptionBudgetForAllNamespaces()).body);
ipcMain.handle('readNamespacedPodDisruptionBudget', async (event, name, namespace) => (await k8sPolicyV1Api.readNamespacedPodDisruptionBudget(name, namespace)).body);


ipcMain.handle('listPriorityClass', async () => (await k8sSchedulingV1Api.listPriorityClass()).body);
ipcMain.handle('readPriorityClass', async (event, name) => (await k8sSchedulingV1Api.readPriorityClass(name)).body);


ipcMain.handle('listRuntimeClass', async () => (await k8sNodeV1Api.listRuntimeClass()).body);
ipcMain.handle('readRuntimeClass', async (event, name) => (await k8sNodeV1Api.readRuntimeClass(name)).body);


ipcMain.handle('listMutatingWebhookConfiguration', async () => (await k8sAdmissionregistrationV1Api.listMutatingWebhookConfiguration()).body);
ipcMain.handle('listValidatingWebhookConfiguration', async () => (await k8sAdmissionregistrationV1Api.listValidatingWebhookConfiguration()).body);
ipcMain.handle('readMutatingWebhookConfiguration', async (event, name) => (await k8sAdmissionregistrationV1Api.readMutatingWebhookConfiguration(name)).body);
ipcMain.handle('readValidatingWebhookConfiguration', async (event, name, namespace) => (await k8sAdmissionregistrationV1Api.readValidatingWebhookConfiguration(name, namespace)).body);


ipcMain.handle('listRoleForAllNamespaces', async () => (await k8sRbacAuthorizationV1Api.listRoleForAllNamespaces()).body);
ipcMain.handle('listRoleBindingForAllNamespaces', async () => (await k8sRbacAuthorizationV1Api.listRoleBindingForAllNamespaces()).body);
ipcMain.handle('listClusterRole', async () => (await k8sRbacAuthorizationV1Api.listClusterRole()).body);
ipcMain.handle('listClusterRoleBinding', async () => (await k8sRbacAuthorizationV1Api.listClusterRoleBinding()).body);
ipcMain.handle('readClusterRoleBinding', async (event, name) => (await k8sRbacAuthorizationV1Api.readClusterRoleBinding(name)).body);
ipcMain.handle('readClusterRole', async (event, name) => (await k8sRbacAuthorizationV1Api.readClusterRole(name)).body);
ipcMain.handle('readNamespacedRoleBinding', async (event, name, namespace) => (await k8sRbacAuthorizationV1Api.readNamespacedRoleBinding(name, namespace)).body);
ipcMain.handle('readNamespacedRole', async (event, name, namespace) => (await k8sRbacAuthorizationV1Api.readNamespacedRole(name, namespace)).body);


// Custom Resource Definitions
ipcMain.handle('listCustomResourceDefinition', async () => (await k8sApiextensionsV1Api.listCustomResourceDefinition()).body);
ipcMain.handle('readCustomResourceDefinition', async (event, name) => (await k8sApiextensionsV1Api.readCustomResourceDefinition(name)).body);

// Custom Resources
ipcMain.handle('listCustomResources', async (event, group, version, plural, namespace) => {
  try {
    if (namespace) {
      return (await k8sCustomObjectsApi.listNamespacedCustomObject(group, version, namespace, plural)).body;
    } else {
      return (await k8sCustomObjectsApi.listClusterCustomObject(group, version, plural)).body;
    }
  } catch (error) {
    console.error('Error listing custom resources:', error);
    throw error;
  }
});

ipcMain.handle('readCustomResource', async (event, group, version, plural, name, namespace) => {
  try {
    if (namespace) {
      return (await k8sCustomObjectsApi.getNamespacedCustomObject(group, version, namespace, plural, name)).body;
    } else {
      return (await k8sCustomObjectsApi.getClusterCustomObject(group, version, plural, name)).body;
    }
  } catch (error) {
    console.error('Error reading custom resource:', error);
    throw error;
  }
});

// Events
ipcMain.handle('listEventForAllNamespaces', async () => (await k8sCoreV1Api.listEventForAllNamespaces()).body);
ipcMain.handle('listNamespacedEvent', async (event, namespace) => (await k8sCoreV1Api.listNamespacedEvent(namespace)).body);

// Port Forwarding
const activePortForwards = new Map<string, PortForwardInfo & { process?: ChildProcess }>();

// Helper function to find an available port
async function findAvailablePort(startPort: number = 8080): Promise<number> {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.listen(startPort, '127.0.0.1', () => {
      const port = (server.address() as net.AddressInfo).port;
      server.close(() => resolve(port));
    });
    server.on('error', () => {
      resolve(findAvailablePort(startPort + 1));
    });
  });
}

ipcMain.handle('createPortForward', async (event, request: PortForwardRequest) => {
  try {
    const id = uuidv4();
    // Use provided port or find an available one
    const localPort = request.localPort || await findAvailablePort();
    const localAddress = request.localAddress || '127.0.0.1';

    // Create port forward info
    const portForwardInfo: PortForwardInfo = {
      id,
      resourceType: request.resourceType,
      resourceName: request.resourceName,
      namespace: request.namespace,
      localPort,
      remotePort: request.remotePort,
      localAddress,
      status: PortForwardStatus.Connecting,
      startTime: new Date(),
      bytesTransferred: { sent: 0, received: 0 }
    };

    // Store in map
    activePortForwards.set(id, portForwardInfo);

    // Get current context for kubectl
    const currentContext = kc.getCurrentContext();
    
    // Build kubectl command
    const args = [
      '--context', currentContext,
      '-n', request.namespace,
      'port-forward',
      `${request.resourceType}/${request.resourceName}`,
      `${localPort}:${request.remotePort}`
    ];

    if (localAddress !== '127.0.0.1') {
      args.push('--address', localAddress);
    }

    // Spawn kubectl port-forward process
    const kubectlProcess = spawn('kubectl', args);

    // Handle stdout
    kubectlProcess.stdout.on('data', (data) => {
      const output = data.toString();
      console.log('Port forward output:', output);
      
      // Check if forwarding is ready
      if (output.includes('Forwarding from')) {
        const forwardInfo = activePortForwards.get(id);
        if (forwardInfo) {
          forwardInfo.status = PortForwardStatus.Active;
          activePortForwards.set(id, { ...forwardInfo, process: kubectlProcess });
        }
      }
    });

    // Handle stderr
    kubectlProcess.stderr.on('data', (data) => {
      console.error('Port forward error:', data.toString());
    });

    // Handle process exit
    kubectlProcess.on('exit', (code, signal) => {
      console.log(`Port forward process exited with code ${code} and signal ${signal}`);
      const forwardInfo = activePortForwards.get(id);
      if (forwardInfo && forwardInfo.status !== PortForwardStatus.Stopping) {
        forwardInfo.status = PortForwardStatus.Failed;
        forwardInfo.error = `Process exited with code ${code}`;
        activePortForwards.set(id, forwardInfo);
      }
      activePortForwards.delete(id);
    });

    // Handle process error
    kubectlProcess.on('error', (err) => {
      console.error('Failed to start port forward:', err);
      const forwardInfo = activePortForwards.get(id);
      if (forwardInfo) {
        forwardInfo.status = PortForwardStatus.Failed;
        forwardInfo.error = err.message;
        activePortForwards.set(id, forwardInfo);
      }
    });

    // Wait a bit to see if the process starts successfully
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Check if process is still running
    if (kubectlProcess.exitCode !== null) {
      throw new Error('Port forward process failed to start');
    }

    return { success: true, forwardId: id, localPort };
  } catch (error: any) {
    console.error('Failed to create port forward:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('stopPortForward', async (event, forwardId: string) => {
  try {
    const portForward = activePortForwards.get(forwardId);
    if (!portForward) {
      return { success: false, error: 'Port forward not found' };
    }

    // Update status
    portForward.status = PortForwardStatus.Stopping;
    activePortForwards.set(forwardId, portForward);

    // Kill the kubectl process
    if (portForward.process && !portForward.process.killed) {
      portForward.process.kill('SIGTERM');
      
      // Force kill after 2 seconds if still running
      setTimeout(() => {
        if (portForward.process && !portForward.process.killed) {
          portForward.process.kill('SIGKILL');
        }
      }, 2000);
    }

    // Remove from active forwards
    activePortForwards.delete(forwardId);

    return { success: true };
  } catch (error: any) {
    console.error('Failed to stop port forward:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('listPortForwards', async () => {
  return Array.from(activePortForwards.values()).map(({ process, ...info }) => info);
});

// Clean up on app quit
app.on('before-quit', async () => {
  // Clean up port forwards
  activePortForwards.forEach((portForward, id) => {
    if (portForward.process && !portForward.process.killed) {
      portForward.process.kill('SIGTERM');
    }
  });
  
  // Stop MCP server
  await stopMCPServer();
});

ipcMain.handle('readNamespacedEvent', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedEvent(name, namespace)).body);

// MCP Server handlers
ipcMain.handle('getMCPConnections', async () => getActiveConnections());
ipcMain.handle('getMCPToolCallHistory', async (event, limit?: number) => getToolCallHistory(limit));
ipcMain.handle('clearMCPToolCallHistory', async () => clearToolCallHistory());
