import { app, BrowserWindow, ipcMain, shell, globalShortcut } from 'electron';
import k8s = require('@kubernetes/client-node');
import { dumpYaml, loadYaml } from '@kubernetes/client-node/dist/yaml';
import * as net from 'net';
import * as path from 'path';
import * as os from 'os';
import * as fs from 'fs';
import { v4 as uuidv4 } from 'uuid';
import { spawn, ChildProcess } from 'child_process';
import { PortForwardInfo, PortForwardRequest } from '../renderer/utils/types';
import { PortForwardStatus } from '../renderer/utils/enums';
import { startMCPServer, stopMCPServer, getToolCallHistory, getActiveConnections, clearToolCallHistory } from './mcp-server';
import { CDPDevUtils } from './cdp-dev-utils';

// Initialize KubeConfig with error handling
let kc: k8s.KubeConfig;
let k8sCoreV1Api: k8s.CoreV1Api;
let k8sAppsV1Api: k8s.AppsV1Api;
let k8sBatchV1Api: k8s.BatchV1Api;
let k8sNetworkingV1Api: k8s.NetworkingV1Api;
let k8sDiscoveryV1Api: k8s.DiscoveryV1Api;
let k8sAutoscalingV2Api: k8s.AutoscalingV2Api;
let k8sPolicyV1Api: k8s.PolicyV1Api;
let k8sStorageV1Api: k8s.StorageV1Api;
let k8sRbacAuthorizationV1Api: k8s.RbacAuthorizationV1Api;
let k8sSchedulingV1Api: k8s.SchedulingV1Api;
let k8sNodeV1Api: k8s.NodeV1Api;
let k8sAdmissionregistrationV1Api: k8s.AdmissionregistrationV1Api;
let k8sApiextensionsV1Api: k8s.ApiextensionsV1Api;
let k8sCustomObjectsApi: k8s.CustomObjectsApi;
let k8sMetricsClient: k8s.Metrics;

// Configure axios defaults for the kubernetes client to handle certificates better
const https = require('https');
const httpsAgent = new https.Agent({
  rejectUnauthorized: false, // This will accept self-signed certificates
});

// Track if Kubernetes is initialized
let isK8sInitialized = false;

// Function to initialize or reinitialize Kubernetes clients
function initializeK8sClients() {
  try {
    // If kc doesn't exist yet, create it
    if (!kc) {
      kc = new k8s.KubeConfig();
      kc.loadFromDefault();
    }
    
    // Apply the agent to the kc before creating API clients
    kc.applytoHTTPSOptions = (opts) => {
      opts.agent = httpsAgent;
      return opts;
    };
    
    k8sCoreV1Api = kc.makeApiClient(k8s.CoreV1Api);
    k8sAppsV1Api = kc.makeApiClient(k8s.AppsV1Api);
    k8sBatchV1Api = kc.makeApiClient(k8s.BatchV1Api);
    k8sNetworkingV1Api = kc.makeApiClient(k8s.NetworkingV1Api);
    k8sDiscoveryV1Api = kc.makeApiClient(k8s.DiscoveryV1Api);
    k8sAutoscalingV2Api = kc.makeApiClient(k8s.AutoscalingV2Api);
    k8sPolicyV1Api = kc.makeApiClient(k8s.PolicyV1Api);
    k8sStorageV1Api = kc.makeApiClient(k8s.StorageV1Api);
    k8sRbacAuthorizationV1Api = kc.makeApiClient(k8s.RbacAuthorizationV1Api);
    k8sSchedulingV1Api = kc.makeApiClient(k8s.SchedulingV1Api);
    k8sNodeV1Api = kc.makeApiClient(k8s.NodeV1Api);
    k8sAdmissionregistrationV1Api = kc.makeApiClient(k8s.AdmissionregistrationV1Api);
    k8sApiextensionsV1Api = kc.makeApiClient(k8s.ApiextensionsV1Api);
    k8sCustomObjectsApi = kc.makeApiClient(k8s.CustomObjectsApi);
    k8sMetricsClient = new k8s.Metrics(kc);
    
    isK8sInitialized = true;
    console.log('Kubernetes clients initialized successfully with context:', kc.getCurrentContext());
  } catch (error) {
    console.error('Failed to initialize Kubernetes clients:', error);
    isK8sInitialized = false;
  }
}

// Try to initialize on startup, but don't fail if it doesn't work
initializeK8sClients();

// Helper function to handle K8s API calls safely
async function handleK8sListRequest(apiCall: () => Promise<any>) {
  if (!isK8sInitialized) {
    return { items: [] };
  }
  try {
    return await apiCall();
  } catch (error) {
    console.error('K8s API error:', error);
    return { items: [] };
  }
}


// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Enable Chrome DevTools Protocol for development debugging
if (process.env.NODE_ENV === 'development' || !app.isPackaged) {
  // Enable remote debugging on port 9223
  app.commandLine.appendSwitch('remote-debugging-port', '9223');
  
  // Optional: Enable debugging for specific domains
  app.commandLine.appendSwitch('enable-logging');
  app.commandLine.appendSwitch('v', '1');
}

const createWindow = (): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.removeMenu()

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Handle mouse navigation buttons
  mainWindow.webContents.on('before-input-event', (event, input) => {
    // Log all mouse events for debugging
    if (input.type === 'mouseDown' || input.type === 'mouseUp') {
      console.log('Mouse event:', input.type, 'button:', input.button, 'typeof:', typeof input.button);
    }
    
    if (input.type === 'mouseDown') {
      // Check for string-based button names
      if (input.button === 'back') {
        console.log('Back button pressed (string)');
        event.preventDefault();
        mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'back' });
      } else if (input.button === 'forward') {
        console.log('Forward button pressed (string)');
        event.preventDefault();
        mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'forward' });
      }
      // Check for numeric button codes (3 = back, 4 = forward on many mice)
      else if (input.button === 3) {
        console.log('Back button pressed (button 3)');
        event.preventDefault();
        mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'back' });
      } else if (input.button === 4) {
        console.log('Forward button pressed (button 4)');
        event.preventDefault();
        mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'forward' });
      }
    }
  });

  // Alternative method using app-command event
  mainWindow.on('app-command', (event, cmd) => {
    console.log('App command:', cmd);
    if (cmd === 'browser-backward') {
      event.preventDefault();
      mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'back' });
    } else if (cmd === 'browser-forward') {
      event.preventDefault();
      mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'forward' });
    }
  });
  
  // Development-only CDP features
  if (process.env.NODE_ENV === 'development' || !app.isPackaged) {
    // Initialize CDP utilities
    const cdpUtils = new CDPDevUtils(mainWindow);
    
    // Log CDP debugging URL
    mainWindow.webContents.on('did-finish-load', () => {
      console.log('\n=== Chrome DevTools Protocol Debugging ===');
      console.log('Main process debugging URL: http://localhost:9223');
      console.log('Renderer process debugging URL:', mainWindow.webContents.getURL());
      console.log('Use chrome://inspect in Chrome/Chromium to connect');
      console.log('=========================================\n');
    });

    // Enable additional CDP features
    mainWindow.webContents.session.setPermissionRequestHandler((webContents, permission, callback) => {
      callback(true);
    });
  }
  
  return mainWindow;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  const mainWindow = createWindow();
  
  // Register keyboard shortcuts for navigation
  globalShortcut.register('Alt+Left', () => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'back' });
    }
  });
  
  globalShortcut.register('Alt+Right', () => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('navigation', { type: 'navigation', direction: 'forward' });
    }
  });
  
  // Start MCP server
  try {
    await startMCPServer();
  } catch (error) {
    console.error('Failed to start MCP server:', error);
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('will-quit', () => {
  // Unregister all shortcuts
  globalShortcut.unregisterAll();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
// Handle the getPods request from the renderer

ipcMain.handle('openExternalLink', (event, url) => {
  shell.openExternal(url);
});

// Add handler to check Kubernetes initialization status
ipcMain.handle('getK8sStatus', () => {
  return {
    initialized: isK8sInitialized,
    error: isK8sInitialized ? null : 'No Kubernetes configuration found'
  };
});

// Contexts
ipcMain.handle('getContexts', () => {
  if (!kc) {
    // Try to load kubeconfig for context operations
    try {
      kc = new k8s.KubeConfig();
      kc.loadFromDefault();
    } catch (error) {
      return [];
    }
  }
  return kc.getContexts();
});

ipcMain.handle('getCurrentContext', () => {
  if (!kc) {
    // Try to load kubeconfig for context operations
    try {
      kc = new k8s.KubeConfig();
      kc.loadFromDefault();
    } catch (error) {
      return null;
    }
  }
  return kc.getCurrentContext();
});

ipcMain.handle('setCurrentContext', (event, name) => {
  if (!kc) {
    // Try to load kubeconfig if not initialized
    try {
      kc = new k8s.KubeConfig();
      kc.loadFromDefault();
    } catch (error) {
      throw new Error('No Kubernetes configuration available');
    }
  }
  kc.setCurrentContext(name);
  
  // Reconfigure the HTTPS agent for the new context
  kc.applytoHTTPSOptions = (opts) => {
    opts.agent = httpsAgent;
    return opts;
  };
  
  // Reinitialize API clients with the new context
  initializeK8sClients();
  
  return name;
});
ipcMain.handle('getContextObject', (event, name) => (kc.getContextObject(name)));
ipcMain.handle('addContext', (event, context) => (kc.addContext(context)));
ipcMain.handle('mergeKubeconfig', async (event, kubeconfigYaml) => {
  try {
    // Get the kubeconfig file path
    const kubeConfigPath = process.env.KUBECONFIG || path.join(os.homedir(), '.kube', 'config');
    
    // Create backup of existing config
    if (fs.existsSync(kubeConfigPath)) {
      const backupPath = `${kubeConfigPath}.backup-${Date.now()}`;
      fs.copyFileSync(kubeConfigPath, backupPath);
    }
    
    // Create a new KubeConfig and load existing config if it exists
    const mergedKc = new k8s.KubeConfig();
    if (fs.existsSync(kubeConfigPath)) {
      mergedKc.loadFromFile(kubeConfigPath);
    }
    
    // Create a temporary KubeConfig to parse the incoming YAML
    const tempKc = new k8s.KubeConfig();
    tempKc.loadFromString(kubeconfigYaml);
    
    // Use the built-in mergeConfig method
    mergedKc.mergeConfig(tempKc);
    
    // Export the merged config as JSON string
    const mergedConfigJson = mergedKc.exportConfig();
    const mergedConfigObj = JSON.parse(mergedConfigJson);
    
    // Convert to YAML and save
    const yamlContent = dumpYaml(mergedConfigObj);
    fs.writeFileSync(kubeConfigPath, yamlContent);
    
    // Reload the global kc with the merged config
    kc.loadFromDefault();
    
    // Reinitialize the API clients with the new config
    k8sCoreV1Api = kc.makeApiClient(k8s.CoreV1Api);
    k8sAppsV1Api = kc.makeApiClient(k8s.AppsV1Api);
    k8sNetworkingV1Api = kc.makeApiClient(k8s.NetworkingV1Api);
    k8sBatchV1Api = kc.makeApiClient(k8s.BatchV1Api);
    k8sRbacAuthorizationV1Api = kc.makeApiClient(k8s.RbacAuthorizationV1Api);
    k8sStorageV1Api = kc.makeApiClient(k8s.StorageV1Api);
    k8sPolicyV1Api = kc.makeApiClient(k8s.PolicyV1Api);
    k8sAutoscalingV2Api = kc.makeApiClient(k8s.AutoscalingV2Api);
    k8sSchedulingV1Api = kc.makeApiClient(k8s.SchedulingV1Api);
    k8sNodeV1Api = kc.makeApiClient(k8s.NodeV1Api);
    k8sAdmissionregistrationV1Api = kc.makeApiClient(k8s.AdmissionregistrationV1Api);
    k8sApiextensionsV1Api = kc.makeApiClient(k8s.ApiextensionsV1Api);
    k8sMetricsClient = new k8s.Metrics(kc);
    
    return { success: true };
  } catch (error) {
    console.error('Error merging kubeconfig:', error);
    return { 
      success: false, 
      error: error.message || 'Failed to merge kubeconfig' 
    };
  }
});

// Nodes
ipcMain.handle('listNode', async () => {
  if (!isK8sInitialized) {
    // Return empty list instead of throwing error to prevent modal dialogs
    return { items: [] };
  }
  return (await k8sCoreV1Api.listNode()).body;
});

ipcMain.handle('readNode', async (event, name) => {
  if (!isK8sInitialized) {
    throw new Error('Kubernetes is not configured. Please check your kubeconfig.');
  }
  return (await k8sCoreV1Api.readNode(name)).body;
});

ipcMain.handle('topNodes', async () => {
  if (!isK8sInitialized) {
    // Return empty array instead of throwing error
    return [];
  }
  return await k8s.topNodes(k8sCoreV1Api);
});
ipcMain.handle('cordonNode', async (event, name) => {
  try {
    const patch = {
      spec: {
        unschedulable: true
      }
    };
    const response = await k8sCoreV1Api.patchNode(
      name, 
      patch, 
      undefined, 
      undefined, 
      undefined, 
      undefined, 
      undefined,
      { headers: { 'Content-Type': k8s.PatchUtils.PATCH_FORMAT_STRATEGIC_MERGE_PATCH } }
    );
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while cordoning the node';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('uncordonNode', async (event, name) => {
  try {
    const patch = {
      spec: {
        unschedulable: false
      }
    };
    const response = await k8sCoreV1Api.patchNode(
      name, 
      patch, 
      undefined, 
      undefined, 
      undefined, 
      undefined, 
      undefined,
      { headers: { 'Content-Type': k8s.PatchUtils.PATCH_FORMAT_STRATEGIC_MERGE_PATCH } }
    );
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while uncordoning the node';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});


// Namespaces
ipcMain.handle('listNamespace', async () => {
  if (!isK8sInitialized) {
    return { items: [] };
  }
  return (await k8sCoreV1Api.listNamespace()).body;
});
ipcMain.handle('readNamespace', async (event, name) => (await k8sCoreV1Api.readNamespace(name)).body);
ipcMain.handle('createNamespace', async (event, payload) => {
  try {
    const response = await k8sCoreV1Api.createNamespace(payload);
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while creating the namespace';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('deleteNamespace', async (event, name) => (await k8sCoreV1Api.deleteNamespace(name)).body);


// Deployments
ipcMain.handle('listDeploymentForAllNamespaces', async () => {
  if (!isK8sInitialized) {
    return { items: [] };
  }
  return (await k8sAppsV1Api.listDeploymentForAllNamespaces()).body;
});
ipcMain.handle('readNamespacedDeployment', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedDeployment(name, namespace)).body);


// ReplicaSets
ipcMain.handle('listReplicaSetForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sAppsV1Api.listReplicaSetForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedReplicaSet', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedReplicaSet(name, namespace)).body);


// StatefulSets
ipcMain.handle('listStatefulSetForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sAppsV1Api.listStatefulSetForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedStatefulSet', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedStatefulSet(name, namespace)).body);


// DaemonSets
ipcMain.handle('listDaemonSetForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sAppsV1Api.listDaemonSetForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedDaemonSet', async (event, name, namespace) => (await k8sAppsV1Api.readNamespacedDaemonSet(name, namespace)).body);


// Pods
ipcMain.handle('listPodForAllNamespaces', async () => {
  if (!isK8sInitialized) {
    return { items: [] };
  }
  return (await k8sCoreV1Api.listPodForAllNamespaces()).body;
});
ipcMain.handle('readNamespacedPod', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedPod(name, namespace)).body);
ipcMain.handle('createNamespacedPod', async (event, namespace, podSpec) => {
  try {
    const response = await k8sCoreV1Api.createNamespacedPod(namespace, podSpec);
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while creating the pod';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('deleteNamespacedPod', async (event, name, namespace) => (await k8sCoreV1Api.deleteNamespacedPod(name, namespace)).body);

// Pod logs
ipcMain.handle('readNamespacedPodLog', async (event, name, namespace, container, options = {}) => {
  try {
    const response = await k8sCoreV1Api.readNamespacedPodLog(
      name,
      namespace,
      container,
      options.follow,
      undefined, // insecureSkipTLSVerifyBackend
      undefined, // limitBytes
      options.pretty,
      options.previous,
      options.sinceSeconds,
      options.tailLines,
      options.timestamps
    );
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while fetching pod logs';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});


// ConfigMaps
ipcMain.handle('listConfigMapForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listConfigMapForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedConfigMap', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedConfigMap(name, namespace)).body);
ipcMain.handle('createNamespacedConfigMap', async (event, namespace, payload) => {
  try {
    const response = await k8sCoreV1Api.createNamespacedConfigMap(namespace, payload);
    return { success: true, data: response.body };
  } catch (error) {
    let errorMessage = 'An error occurred while creating the config map';
    if (error.response && error.response.body && error.response.body.message) {
      errorMessage = error.response.body.message;
    }
    return { success: false, error: errorMessage };
  }
});
ipcMain.handle('deleteNamespacedConfigMap', async (event, name, namespace) => (await k8sCoreV1Api.deleteNamespacedConfigMap(name, namespace)).body);




ipcMain.handle('listJobForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sBatchV1Api.listJobForAllNamespaces()).body);
});
ipcMain.handle('listCronJobForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sBatchV1Api.listCronJobForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedCronJob', async (event, name, namespace) => (await k8sBatchV1Api.readNamespacedCronJob(name, namespace)).body);
ipcMain.handle('readNamespacedJob', async (event, name, namespace) => (await k8sBatchV1Api.readNamespacedJob(name, namespace)).body);


ipcMain.handle('listServiceForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listServiceForAllNamespaces()).body);
});
ipcMain.handle('listEndpointsForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listEndpointsForAllNamespaces()).body);
});

ipcMain.handle('listSecretForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listSecretForAllNamespaces()).body);
});
ipcMain.handle('listResourceQuotaForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listResourceQuotaForAllNamespaces()).body);
});
ipcMain.handle('listLimitRangeForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listLimitRangeForAllNamespaces()).body);
});
ipcMain.handle('listPersistentVolumeClaimForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listPersistentVolumeClaimForAllNamespaces()).body);
});
ipcMain.handle('listPersistentVolume', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listPersistentVolume()).body);
});
ipcMain.handle('listServiceAccountForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listServiceAccountForAllNamespaces()).body);
});
ipcMain.handle('listNamespacedPod', async (event, namespace, ...args) => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listNamespacedPod(namespace, ...args)).body);
});

ipcMain.handle('readNamespacedService', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedService(name, namespace)).body);

ipcMain.handle('readNamespacedSecret', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedSecret(name, namespace)).body);
ipcMain.handle('readNamespacedResourceQuota', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedResourceQuota(name, namespace)).body);
ipcMain.handle('readNamespacedLimitRange', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedLimitRange(name, namespace)).body);
ipcMain.handle('readNamespacedEndpoints', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedEndpoints(name, namespace)).body);

ipcMain.handle('readNamespacedServiceAccount', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedServiceAccount(name, namespace)).body);
ipcMain.handle('readNamespacedPersistentVolumeClaim', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedPersistentVolumeClaim(name, namespace)).body);
ipcMain.handle('readPersistentVolume', async (event, name) => (await k8sCoreV1Api.readPersistentVolume(name)).body);



ipcMain.handle('listIngressForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sNetworkingV1Api.listIngressForAllNamespaces()).body);
});
ipcMain.handle('listIngressClass', async () => {
  return handleK8sListRequest(async () => (await k8sNetworkingV1Api.listIngressClass()).body);
});
ipcMain.handle('listNetworkPolicyForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sNetworkingV1Api.listNetworkPolicyForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedIngress', async (event, name, namespace) => (await k8sNetworkingV1Api.readNamespacedIngress(name, namespace)).body);
ipcMain.handle('readIngressClass', async (event, name) => (await k8sNetworkingV1Api.readIngressClass(name)).body);
ipcMain.handle('readNamespacedNetworkPolicy', async (event, name, namespace) => (await k8sNetworkingV1Api.readNamespacedNetworkPolicy(name, namespace)).body);


ipcMain.handle('listEndpointSliceForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sDiscoveryV1Api.listEndpointSliceForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedEndpointSlice', async (event, name, namespace) => (await k8sDiscoveryV1Api.readNamespacedEndpointSlice(name, namespace)).body);


ipcMain.handle('listVolumeAttachment', async () => {
  return handleK8sListRequest(async () => (await k8sStorageV1Api.listVolumeAttachment()).body);
});
ipcMain.handle('listStorageClass', async () => {
  return handleK8sListRequest(async () => (await k8sStorageV1Api.listStorageClass()).body);
});
ipcMain.handle('listCSINode', async () => {
  return handleK8sListRequest(async () => (await k8sStorageV1Api.listCSINode()).body);
});
ipcMain.handle('listCSIDriver', async () => {
  return handleK8sListRequest(async () => (await k8sStorageV1Api.listCSIDriver()).body);
});
ipcMain.handle('readCSIDriver', async (event, name) => (await k8sStorageV1Api.readCSIDriver(name)).body);
ipcMain.handle('readCSINode', async (event, name) => (await k8sStorageV1Api.readCSINode(name)).body);
ipcMain.handle('readStorageClass', async (event, name) => (await k8sStorageV1Api.readStorageClass(name)).body);
ipcMain.handle('readVolumeAttachment', async (event, name) => (await k8sStorageV1Api.readVolumeAttachment(name)).body);


ipcMain.handle('listHorizontalPodAutoscalerForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sAutoscalingV2Api.listHorizontalPodAutoscalerForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedHorizontalPodAutoscaler', async (event, name, namespace) => (await k8sAutoscalingV2Api.readNamespacedHorizontalPodAutoscaler(name, namespace)).body);


ipcMain.handle('listPodDisruptionBudgetForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sPolicyV1Api.listPodDisruptionBudgetForAllNamespaces()).body);
});
ipcMain.handle('readNamespacedPodDisruptionBudget', async (event, name, namespace) => (await k8sPolicyV1Api.readNamespacedPodDisruptionBudget(name, namespace)).body);


ipcMain.handle('listPriorityClass', async () => {
  return handleK8sListRequest(async () => (await k8sSchedulingV1Api.listPriorityClass()).body);
});
ipcMain.handle('readPriorityClass', async (event, name) => (await k8sSchedulingV1Api.readPriorityClass(name)).body);


ipcMain.handle('listRuntimeClass', async () => {
  return handleK8sListRequest(async () => (await k8sNodeV1Api.listRuntimeClass()).body);
});
ipcMain.handle('readRuntimeClass', async (event, name) => (await k8sNodeV1Api.readRuntimeClass(name)).body);


ipcMain.handle('listMutatingWebhookConfiguration', async () => {
  return handleK8sListRequest(async () => (await k8sAdmissionregistrationV1Api.listMutatingWebhookConfiguration()).body);
});
ipcMain.handle('listValidatingWebhookConfiguration', async () => {
  return handleK8sListRequest(async () => (await k8sAdmissionregistrationV1Api.listValidatingWebhookConfiguration()).body);
});
ipcMain.handle('readMutatingWebhookConfiguration', async (event, name) => (await k8sAdmissionregistrationV1Api.readMutatingWebhookConfiguration(name)).body);
ipcMain.handle('readValidatingWebhookConfiguration', async (event, name, namespace) => (await k8sAdmissionregistrationV1Api.readValidatingWebhookConfiguration(name, namespace)).body);


ipcMain.handle('listRoleForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sRbacAuthorizationV1Api.listRoleForAllNamespaces()).body);
});
ipcMain.handle('listRoleBindingForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sRbacAuthorizationV1Api.listRoleBindingForAllNamespaces()).body);
});
ipcMain.handle('listClusterRole', async () => {
  return handleK8sListRequest(async () => (await k8sRbacAuthorizationV1Api.listClusterRole()).body);
});
ipcMain.handle('listClusterRoleBinding', async () => {
  return handleK8sListRequest(async () => (await k8sRbacAuthorizationV1Api.listClusterRoleBinding()).body);
});
ipcMain.handle('readClusterRoleBinding', async (event, name) => (await k8sRbacAuthorizationV1Api.readClusterRoleBinding(name)).body);
ipcMain.handle('readClusterRole', async (event, name) => (await k8sRbacAuthorizationV1Api.readClusterRole(name)).body);
ipcMain.handle('readNamespacedRoleBinding', async (event, name, namespace) => (await k8sRbacAuthorizationV1Api.readNamespacedRoleBinding(name, namespace)).body);
ipcMain.handle('readNamespacedRole', async (event, name, namespace) => (await k8sRbacAuthorizationV1Api.readNamespacedRole(name, namespace)).body);


// Custom Resource Definitions
ipcMain.handle('listCustomResourceDefinition', async () => {
  return handleK8sListRequest(async () => (await k8sApiextensionsV1Api.listCustomResourceDefinition()).body);
});
ipcMain.handle('readCustomResourceDefinition', async (event, name) => (await k8sApiextensionsV1Api.readCustomResourceDefinition(name)).body);

// Custom Resources
ipcMain.handle('listCustomResources', async (event, group, version, plural, namespace) => {
  try {
    if (namespace) {
      return (await k8sCustomObjectsApi.listNamespacedCustomObject(group, version, namespace, plural)).body;
    } else {
      return (await k8sCustomObjectsApi.listClusterCustomObject(group, version, plural)).body;
    }
  } catch (error) {
    console.error('Error listing custom resources:', error);
    throw error;
  }
});

ipcMain.handle('readCustomResource', async (event, group, version, plural, name, namespace) => {
  try {
    if (namespace) {
      return (await k8sCustomObjectsApi.getNamespacedCustomObject(group, version, namespace, plural, name)).body;
    } else {
      return (await k8sCustomObjectsApi.getClusterCustomObject(group, version, plural, name)).body;
    }
  } catch (error) {
    console.error('Error reading custom resource:', error);
    throw error;
  }
});

// Events
ipcMain.handle('listEventForAllNamespaces', async () => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listEventForAllNamespaces()).body);
});
ipcMain.handle('listNamespacedEvent', async (event, namespace) => {
  return handleK8sListRequest(async () => (await k8sCoreV1Api.listNamespacedEvent(namespace)).body);
});

// Port Forwarding
const activePortForwards = new Map<string, PortForwardInfo & { process?: ChildProcess }>();

// Helper function to find an available port
async function findAvailablePort(startPort: number = 8080): Promise<number> {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.listen(startPort, '127.0.0.1', () => {
      const port = (server.address() as net.AddressInfo).port;
      server.close(() => resolve(port));
    });
    server.on('error', () => {
      resolve(findAvailablePort(startPort + 1));
    });
  });
}

ipcMain.handle('createPortForward', async (event, request: PortForwardRequest) => {
  try {
    const id = uuidv4();
    // Use provided port or find an available one
    const localPort = request.localPort || await findAvailablePort();
    const localAddress = request.localAddress || '127.0.0.1';

    // Create port forward info
    const portForwardInfo: PortForwardInfo = {
      id,
      resourceType: request.resourceType,
      resourceName: request.resourceName,
      namespace: request.namespace,
      localPort,
      remotePort: request.remotePort,
      localAddress,
      status: PortForwardStatus.Connecting,
      startTime: new Date(),
      bytesTransferred: { sent: 0, received: 0 }
    };

    // Store in map
    activePortForwards.set(id, portForwardInfo);

    // Get current context for kubectl
    const currentContext = kc.getCurrentContext();
    
    // Build kubectl command
    const args = [
      '--context', currentContext,
      '-n', request.namespace,
      'port-forward',
      `${request.resourceType}/${request.resourceName}`,
      `${localPort}:${request.remotePort}`
    ];

    if (localAddress !== '127.0.0.1') {
      args.push('--address', localAddress);
    }

    // Spawn kubectl port-forward process
    const kubectlProcess = spawn('kubectl', args);

    // Handle stdout
    kubectlProcess.stdout.on('data', (data) => {
      const output = data.toString();
      console.log('Port forward output:', output);
      
      // Check if forwarding is ready
      if (output.includes('Forwarding from')) {
        const forwardInfo = activePortForwards.get(id);
        if (forwardInfo) {
          forwardInfo.status = PortForwardStatus.Active;
          activePortForwards.set(id, { ...forwardInfo, process: kubectlProcess });
        }
      }
    });

    // Handle stderr
    kubectlProcess.stderr.on('data', (data) => {
      console.error('Port forward error:', data.toString());
    });

    // Handle process exit
    kubectlProcess.on('exit', (code, signal) => {
      console.log(`Port forward process exited with code ${code} and signal ${signal}`);
      const forwardInfo = activePortForwards.get(id);
      if (forwardInfo && forwardInfo.status !== PortForwardStatus.Stopping) {
        forwardInfo.status = PortForwardStatus.Failed;
        forwardInfo.error = `Process exited with code ${code}`;
        activePortForwards.set(id, forwardInfo);
      }
      activePortForwards.delete(id);
    });

    // Handle process error
    kubectlProcess.on('error', (err) => {
      console.error('Failed to start port forward:', err);
      const forwardInfo = activePortForwards.get(id);
      if (forwardInfo) {
        forwardInfo.status = PortForwardStatus.Failed;
        forwardInfo.error = err.message;
        activePortForwards.set(id, forwardInfo);
      }
    });

    // Wait a bit to see if the process starts successfully
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Check if process is still running
    if (kubectlProcess.exitCode !== null) {
      throw new Error('Port forward process failed to start');
    }

    return { success: true, forwardId: id, localPort };
  } catch (error: any) {
    console.error('Failed to create port forward:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('stopPortForward', async (event, forwardId: string) => {
  try {
    const portForward = activePortForwards.get(forwardId);
    if (!portForward) {
      return { success: false, error: 'Port forward not found' };
    }

    // Update status
    portForward.status = PortForwardStatus.Stopping;
    activePortForwards.set(forwardId, portForward);

    // Kill the kubectl process
    if (portForward.process && !portForward.process.killed) {
      portForward.process.kill('SIGTERM');
      
      // Force kill after 2 seconds if still running
      setTimeout(() => {
        if (portForward.process && !portForward.process.killed) {
          portForward.process.kill('SIGKILL');
        }
      }, 2000);
    }

    // Remove from active forwards
    activePortForwards.delete(forwardId);

    return { success: true };
  } catch (error: any) {
    console.error('Failed to stop port forward:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('listPortForwards', async () => {
  return Array.from(activePortForwards.values()).map(({ process, ...info }) => info);
});

// Clean up on app quit
app.on('before-quit', async () => {
  // Clean up port forwards
  activePortForwards.forEach((portForward, id) => {
    if (portForward.process && !portForward.process.killed) {
      portForward.process.kill('SIGTERM');
    }
  });
  
  // Stop MCP server
  await stopMCPServer();
});

ipcMain.handle('readNamespacedEvent', async (event, name, namespace) => (await k8sCoreV1Api.readNamespacedEvent(name, namespace)).body);

// MCP Server handlers
ipcMain.handle('getMCPConnections', async () => getActiveConnections());
ipcMain.handle('getMCPToolCallHistory', async (event, limit?: number) => getToolCallHistory(limit));
ipcMain.handle('clearMCPToolCallHistory', async () => clearToolCallHistory());

// Generic Apply handler
ipcMain.handle('apply', async (event, yamlContent: string) => {
  try {
    const resources = loadYaml(yamlContent);
    const resourceArray = Array.isArray(resources) ? resources : [resources];
    
    const results = [];
    for (const resource of resourceArray) {
      if (!resource || !resource.kind) {
        throw new Error('Invalid resource: missing kind');
      }

      const namespace = resource.metadata?.namespace || 'default';
      const name = resource.metadata?.name;

      try {
        let result;
        switch (resource.kind) {
          case 'Namespace':
            result = await k8sCoreV1Api.createNamespace(resource);
            break;
          case 'Deployment':
            result = await k8sAppsV1Api.createNamespacedDeployment(namespace, resource);
            break;
          case 'Service':
            result = await k8sCoreV1Api.createNamespacedService(namespace, resource);
            break;
          case 'ConfigMap':
            result = await k8sCoreV1Api.createNamespacedConfigMap(namespace, resource);
            break;
          case 'Secret':
            result = await k8sCoreV1Api.createNamespacedSecret(namespace, resource);
            break;
          case 'Pod':
            result = await k8sCoreV1Api.createNamespacedPod(namespace, resource);
            break;
          case 'StatefulSet':
            result = await k8sAppsV1Api.createNamespacedStatefulSet(namespace, resource);
            break;
          case 'DaemonSet':
            result = await k8sAppsV1Api.createNamespacedDaemonSet(namespace, resource);
            break;
          case 'Job':
            result = await k8sBatchV1Api.createNamespacedJob(namespace, resource);
            break;
          case 'CronJob':
            result = await k8sBatchV1Api.createNamespacedCronJob(namespace, resource);
            break;
          case 'Ingress':
            result = await k8sNetworkingV1Api.createNamespacedIngress(namespace, resource);
            break;
          case 'PersistentVolumeClaim':
            result = await k8sCoreV1Api.createNamespacedPersistentVolumeClaim(namespace, resource);
            break;
          case 'ServiceAccount':
            result = await k8sCoreV1Api.createNamespacedServiceAccount(namespace, resource);
            break;
          case 'Role':
            result = await k8sRbacAuthorizationV1Api.createNamespacedRole(namespace, resource);
            break;
          case 'RoleBinding':
            result = await k8sRbacAuthorizationV1Api.createNamespacedRoleBinding(namespace, resource);
            break;
          case 'ClusterRole':
            result = await k8sRbacAuthorizationV1Api.createClusterRole(resource);
            break;
          case 'ClusterRoleBinding':
            result = await k8sRbacAuthorizationV1Api.createClusterRoleBinding(resource);
            break;
          case 'NetworkPolicy':
            result = await k8sNetworkingV1Api.createNamespacedNetworkPolicy(namespace, resource);
            break;
          case 'HorizontalPodAutoscaler':
            result = await k8sAutoscalingV2Api.createNamespacedHorizontalPodAutoscaler(namespace, resource);
            break;
          case 'PodDisruptionBudget':
            result = await k8sPolicyV1Api.createNamespacedPodDisruptionBudget(namespace, resource);
            break;
          case 'LimitRange':
            result = await k8sCoreV1Api.createNamespacedLimitRange(namespace, resource);
            break;
          case 'ResourceQuota':
            result = await k8sCoreV1Api.createNamespacedResourceQuota(namespace, resource);
            break;
          case 'PersistentVolume':
            result = await k8sCoreV1Api.createPersistentVolume(resource);
            break;
          case 'StorageClass':
            result = await k8sStorageV1Api.createStorageClass(resource);
            break;
          default:
            // Try to handle as a custom resource
            if (resource.apiVersion && resource.apiVersion.includes('/')) {
              const [group, version] = resource.apiVersion.split('/');
              const plural = resource.kind.toLowerCase() + 's'; // Simple pluralization
              if (namespace && namespace !== 'default') {
                result = await k8sCustomObjectsApi.createNamespacedCustomObject(
                  group, version, namespace, plural, resource
                );
              } else {
                result = await k8sCustomObjectsApi.createClusterCustomObject(
                  group, version, plural, resource
                );
              }
            } else {
              throw new Error(`Unsupported resource kind: ${resource.kind}`);
            }
        }
        results.push(result.body);
      } catch (error) {
        // If create fails, try to update instead
        if (error.response?.statusCode === 409 && name) {
          try {
            let result;
            switch (resource.kind) {
              case 'Namespace':
                result = await k8sCoreV1Api.patchNamespace(name, resource, undefined, undefined, undefined, undefined, { headers: { 'Content-Type': 'application/merge-patch+json' } });
                break;
              case 'Deployment':
                result = await k8sAppsV1Api.patchNamespacedDeployment(name, namespace, resource, undefined, undefined, undefined, undefined, { headers: { 'Content-Type': 'application/merge-patch+json' } });
                break;
              case 'Service':
                result = await k8sCoreV1Api.patchNamespacedService(name, namespace, resource, undefined, undefined, undefined, undefined, { headers: { 'Content-Type': 'application/merge-patch+json' } });
                break;
              case 'ConfigMap':
                result = await k8sCoreV1Api.patchNamespacedConfigMap(name, namespace, resource, undefined, undefined, undefined, undefined, { headers: { 'Content-Type': 'application/merge-patch+json' } });
                break;
              case 'Secret':
                result = await k8sCoreV1Api.patchNamespacedSecret(name, namespace, resource, undefined, undefined, undefined, undefined, { headers: { 'Content-Type': 'application/merge-patch+json' } });
                break;
              // Add more patch cases as needed
              default:
                throw error;
            }
            results.push(result.body);
          } catch (patchError) {
            throw patchError;
          }
        } else {
          throw error;
        }
      }
    }

    return { success: true, data: results.length === 1 ? results[0] : results };
  } catch (error) {
    console.error('Apply error:', error);
    return { 
      success: false, 
      error: error.response?.body?.message || error.message || 'Failed to apply resource' 
    };
  }
});
